# Generated by Django 2.0.7 on 2018-09-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('emailAddress', models.TextField(null=True)),
                ('phoneNumber', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MockTrial.Person')),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('gradClass', models.CharField(max_length=4, null=True)),
                ('studies', models.TextField(null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
            ],
            bases=('MockTrial.person',),
        ),
    ]
