# Generated by Django 2.0.7 on 2018-08-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockTrial', '0002_faq_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
