# Generated by Django 2.0.7 on 2018-08-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockTrial', '0003_teammembers_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='photo',
            field=models.FileField(upload_to='mocktrialweb/static/'),
        ),
    ]
