# Generated by Django 2.0.7 on 2018-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockTrial', '0004_auto_20180818_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
