# Generated by Django 2.0.7 on 2018-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockTrial', '0005_auto_20180818_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
