# Generated by Django 2.0.7 on 2018-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockTrial', '0006_auto_20180818_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='classnum',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammembers',
            name='major',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
