# Generated by Django 2.0.7 on 2018-09-08 21:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockTrial', '0009_invitational_mainline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='classnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
